### ISSUE TITLE
Autogenerate object variables

### ISSUE THREAD

**Issue by sgpthomas** [DSEF/pydsef#3]
Automatically do `self.var = conf['var']` for every key in the configuration dictionary

**Comment by wlloyd** [comment]
I don't understand what this one means.

**Comment by sgpthomas** [comment]
We have a dictionary called `conf` and we want to add all of its keys as attributes of `self`. So, if there is a key named `var`, instead of accessing it with conf['var'] you could access it with `self.var`. This is mainly a convenience thing that Yousif wanted to add.
